server:
  port: 9002
spring:
  application:
    name: tensquare-base   # 服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.136.0:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6869/eureka

jwt:
  config:
    key: lingzun
    ttl: 36000000