server:
  port: 9012
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6869/eureka
zuul:
  routes:
    tensquare-gathering:  #活动
        path: /gathering/**  #配置请求URL的请求规则
        serviceId: tensquare-gathering  #指定eureka注册中心的服务id
    tensquare-article:  #文章
      path: /article/**  #配置请求URL的请求规则
      serviceId: tensquare-article  #指定eureka注册中心的服务id
    tensquare-base:  #基础
      path: /base/**  #配置请求URL的请求规则
      serviceId: tensquare-base  #指定eureka注册中心的服务id
    tensquare-friend:  #交友
      path: /friend/**  #配置请求URL的请求规则
      serviceId: tensquare-friend  #指定eureka注册中心的服务id
    tensquare-qa:  #问答
      path: /qa/**  #配置请求URL的请求规则
      serviceId: tensquare-qa  #指定eureka注册中心的服务id
    tensquare-recruit:  #招聘
      path: /recruit/**  #配置请求URL的请求规则
      serviceId: tensquare-recruit  #指定eureka注册中心的服务id
    tensquare-spit:  #吐槽
      path: /spit/**  #配置请求URL的请求规则
      serviceId: tensquare-spit  #指定eureka注册中心的服务id
    tensquare-user:  #用户
      path: /user/**  #配置请求URL的请求规则
      serviceId: tensquare-user  #指定eureka注册中心的服务id


jwt:
  config:
    key: lingzun
    ttl: 36000000