server:
  port: 9007
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 39.99.136.0
      database: spitdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6869/eureka