server: 
  port: 9009
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.99.136.0:3306/tensquare_user?characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
    generate-ddl: true
  redis:
    host: 39.99.136.0
  rabbitmq:
    host: 39.99.136.0
    username: guest
    password: guest

jwt:
  config:
    key: lingzun
    ttl: 36000000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6869/eureka